import '@/styles/globals.css'
import Providers from '@/components/Providers'

export const metadata = {
  title: 'Chat App | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
